service: serverless-express-vue-app

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt dynamodbSessionTable.Arn
  apiGateway:
    binaryMediaTypes:
      - '*/*'
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*
        Condition:
          IpAddress:
            aws:SourceIp:
              - '${param:ipaddress1}'

package:
  patterns:
    - config
    - dist
    - srv/*
    - package.json
    - yarn.lock
    - '!.github'
    - '!.vscode'
    - '!env'
    - '!public'
    - '!src'
    - '!**.cjs'
    - '!.prettierrc.json'
    - '!index.html'
    - '!jsconfig.json'
    - '!README.md'
    - '!renovate.json'
    - '!vite.config.js'

plugins:
  - serverless-offline

custom:
  defaultStage: local

resources:
  Resources:
    dynamodbSessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-express-vue-app-sessions
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true

functions:
  sls-express:
    name: sls-express-lambda-${sls:stage}
    handler: ./srv/lambda.handler
    timeout: 5
    environment:
      NODE_ENV: ${file(./env/${self:provider.stage}.json):ENV}
      CLIENT_ID: ${param:CLIENT_ID}
      CLIENT_SECRET: ${param:CLIENT_SECRET}
      REDIRECT_URI: ${param:REDIRECT_URI}
      COOKIE_SECRET: ${param:COOKIE_SECRET}
    events:
      # HTTP API endpoint (API Gateway v1) <- リソースポリシーでIP制限するため
      - http:
          method: get
          path: /{any+}
