openapi: 3.0.0
info:
  title: error.v1
  description: エラー共通モデル
  version: '1.0'
  contact:
    name: yuta-katayama-23
    email: yuta-katayama-23@example.com
servers:
  - url: 'http://localhost:3000'
    description: local development
paths: {}
components:
  schemas:
    error:
      title: error
      type: object
      additionalProperties: false
      description: |-
        エラーレスポンス用の汎用モデル  
        codeによりAPI呼び出し側でエラーによる処理分岐を行う事もできます（codeはエラー発生個所に基づいて作成される一意のIDになります）
      properties:
        message:
          type: string
          description: エラーメッセージ
          example: data not found
          minLength: 1
        errors:
          type: array
          minItems: 1
          maxItems: 100
          items:
            type: object
            properties:
              message:
                type: string
                description: エラーメッセージ
                example: data not found
            required:
              - message
        status_code:
          type: integer
          description: HTTPのステータスコード
          example: 404
          minimum: 400
        code:
          type: string
          description: エラーコード
          minLength: 32
          maxLength: 32
          pattern: '^[a-z0-9]{32}$'
          example: 098f6bcd4621d373cade4e832627b4f6
        path:
          type: string
          description: エラー発生パス
          example: 'GET:/api/v1/user'
          pattern: '^(GET|POST|PATCH|PUT|DELETE):\/'
      required:
        - message
        - errors
        - status_code
        - code
        - path
