name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NGINX_DIR: ./config/for_ci_nginx

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: run lint
        run: yarn lint

      - name: build
        run: yarn build:dev

      - name: docker compose up
        run: docker compose up -d

      - name: docker logs express
        run: docker logs express

      # - name: wait for nginx
      #   run: docker run --network host --rm appropriate/curl --retry 10 --retry-connrefused --retry-delay 5 --retry-max-time 60 -v http://localhost:8080

      - name: test
        run: yarn test
